### ISSUE TITLE
python3-mb: transcoding

### ISSUE THREAD

**Issue by pimzand** [jack-cli-cd-ripper/jack#20]
It should be possible to encode to mp3, m4a and ogg from flac files instead of from wav files only.

This could be a two-step process, ie decode to wav first, or a single command line.

**Comment by pimzand** [comment]
implemented in commit 606c42c3a9881bbda42a9bbb3810590b1db41a80

**Comment by pimzand** [comment]
Works just wonderful with a large --encoders number on a fast multi-core CPU!
Supported only for lossless to lossy formats, so currently flac->mp3, flac->m4a and flac->ogg. 
Doesn't require any command line option. Just pretend the .wav's are there when in fact there are .flac's only,
and encode to mp3. m4a or ogg.

**Comment by zzarne** [comment]
I did test this a bit last weekend and it worked great for me, too. It's crazy-fast, being mostly IO-bound when not using a SSD.

This feature (among others) made me switch to flac for archiving my collection.
