### ISSUE TITLE
python3-mb: README.md is now inappropriate

### ISSUE THREAD

**Issue by pimzand** [jack-cli-cd-ripper/jack#31]
The README.md is copied from my fork and should now reflect its new status

**Comment by pimzand** [comment]
Fixed in f46e4f84c6ce75ec81e21307675b52bd98e98ac9

**Comment by zzarne** [comment]
We should try to remember to from now on change the READMEs content in jack/argv.py and then generate a new one with jack --readme README.md and commit it.
