### ISSUE TITLE
Make doc a little more consistent

### ISSUE THREAD

**Issue by madarche** [jack-cli-cd-ripper/jack#4]
Reformat some text files to Markdown.

Rewrite the root README file.

**Comment by madarche** [comment]
@gaetano-guerriero are you OK to reformat the root README to Markdown? I'm asking because in the Python word it's more REST. But I prefer Markdown to REST.

**Comment by gaetano-guerriero** [comment]
Markdown is ok :+1:

**Comment by madarche** [comment]
OK. Thanks @gaetano-guerriero
