### ISSUE TITLE
Default to the Python 3 version of jack

### ISSUE THREAD

**Issue by zzarne** [jack-cli-cd-ripper/jack#46]
I want to discuss two issues here:

1. Are we ready to default the Python 3 version?
2. How do we do it?

I think we are ready, but maybe we want to fix #16 first.

I've never done this, but it should be as simple as
```sh
git checkout python3-mb
git checkout -b main
git push --set-upstream origin main
```
and then change the default branch in github Settings->Branches to main.

We then could rename the master branch to e.g. python2 to avoid confusion.

What do you say? Comments welcome.

**Comment by pimzand** [comment]
I was going to propose the same, and ask the same.

Would clones be able to pull afterwards without issues, without any changes on their side?

**Comment by pimzand** [comment]
Issue #16 is about a feature that isn't present in the current default version.
Users could keep using freedb/gnudb if it is that important to them.

**Comment by zzarne** [comment]
> Would clones be able to pull afterwards without issues, without any changes on their side?

As long as we don't rename the 'master' branch, existing clones would pull from the same branch as before. New clones would get the new default branch, which would be 'main', i.e. Python 3. So we won't rename the 'master' branch in the near future.

**Comment by madmartin** [comment]
Maybe you can update the repository "About" description with hints about the meaning of the branches. I remember it took a while to figure out the python3 version is in a separate branch...

**Comment by pimzand** [comment]
It appears the default can be set using the web interface:
https://github.com/jack-cli-cd-ripper/jack/settings/branches

**Comment by pimzand** [comment]
Switched branches using the web interface. Closing.
