### ISSUE TITLE
do we still need and want to support plugins?

### ISSUE THREAD

**Issue by pimzand** [jack-cli-cd-ripper/jack#49]
It may have become too complex to add helpers using plugins.

**Comment by zzarne** [comment]
My opinion: no. To implement a helper plugin one needs to understand so much of jack's inner workings that adding the helper to jack directly is not harder. Then sending a pull request allows others to benefit as well.

**Comment by pimzand** [comment]
Agreed. There are two example plugins. One for an alternative FreeDB server location, one for an alternative encoder.
The alternative FreeDB server location shouldn't require a plugin, and an alternative encoder requires much more than just a helper definition.

We should probably remove the sample plugins, and maybe the plugin code too?

**Comment by pimzand** [comment]
fixed in c5d05b81e7aad727a056e936be4337fc5fcd31f5
