### ISSUE TITLE
support only python-discid as Python libdiscid wrapper

### ISSUE THREAD

**Issue by pimzand** [jack-cli-cd-ripper/jack#50]
The python3-mb branch of Jack depends on a C library called libdiscid (https://musicbrainz.org/doc/libdiscid).
There are two competing Python wrappers for this library:

python-discid, using ctypes (no compilation)
python-libdiscid, using cython (compiled)

@pimzand started coding using python-libdiscid, because that was available as a package in the distro he was using (Fedora).
@zzarne added python-discid, because apparently, python-libdiscid cannot be installed using pip.

As a result, both libraries are now supported using a wrapper.

I propose we remove this wrapper and support python-discid directly, as the only supported wrapper.
Because:
- python-discid is now available as a package in Fedora
- python-discid is the wrapper used by MusicBrainz Picard
- python-discid can be installed with pip

The benefits are:
- easier to read code
- easier documentation
- easier to detect that requirements are met at runtime and install time

**Comment by zzarne** [comment]
I don't see a python-discid package for Ubuntu (and probably Debian), only python-libdiscid. Getting rid of python-libdiscid would make it harder to package jack for those distributions.

**Comment by pimzand** [comment]
Indeed. I see there's a PPA for discid, but that may not be preferable.
Interesting to see that Picard for Ubuntu depends on python3-libdiscid, where on Fedora it depends python3-discid.
Arch Linux seems to support python-discid only...
So let's leave it this way.

**Comment by madmartin** [comment]
> Indeed. I see there's a PPA for discid, but that may not be preferable. Interesting to see that Picard for Ubuntu depends on python3-libdiscid, where on Fedora it depends python3-discid. Arch Linux seems to support python-discid only... So let's leave it this way.

And Gentoo offers

[U] dev-python/python-discid
     Available versions:  1.2.0 (~)1.2.0-r1^t {doc test PYTHON_TARGETS="python3_8 python3_9 python3_10"}
     Installed versions:  1.2.0(12:29:02 10/04/21)(-doc PYTHON_TARGETS="python3_9 python3_10 -python3_8")
     Homepage:            https://github.com/JonnyJD/python-discid
     Description:         Python bindings for libdiscid

[I] media-libs/libdiscid
     Available versions:  0.6.2
     Installed versions:  0.6.2(00:38:22 09/11/20)
     Homepage:            http://musicbrainz.org/doc/libdiscid
     Description:         Client library to create MusicBrainz enabled tagging applications

**Comment by pimzand** [comment]
Updated the documentation in c1366fc245afb7d9c9f02a89519ea64ccbed2f7c
