### ISSUE TITLE
switch from dateparser to dateutil

### ISSUE THREAD

**Issue by pimzand** [jack-cli-cd-ripper/jack#51]
Jack (python3-mb) uses dateparser to parse the Last-Modified date string from album art downloads.

Current dateparser is broken and is taking forever to get fixed, even though a solution has been proposed.
See https://github.com/scrapinghub/dateparser/issues/1052
This mostly affects users that install their python libraries using their Linux distro.

dateparser can be replaced with dateutil which appears to be a more popular library.

**Comment by madmartin** [comment]
I tried to build a more recent package for gentoo, and found the dateparser library not packaged in gentoo. Then I  tried to package dateparser  myself and fount it a nightmare to package.
dateutil is available in gentoo, so I appreciate to switch over to dateutil.

**Comment by pimzand** [comment]
Fixed in commit https://github.com/jack-cli-cd-ripper/jack/commit/4ed084d15dcd13ac66122a0ee1919865d114fd75
